export const table = [
  {
    name: "Ese Curtis",
    email: "whoami@gmail.com",
    image: "",
    gender: "Male",
    number: "09121232123",
    date: "2 Days Ago",
    status: "Active",
    location: "28355 Hane road, Vista",
  },
  {
    name: "Alice Johnson",
    email: "alice@example.com",
    image: "",
    gender: "Female",
    number: "555-123-4567",
    date: "1 Week Ago",
    status: "Pending",
    location: "771 Jovanny Turnpike",
  },
  {
    name: "John Smith",
    email: "john@example.com",
    image: "",
    gender: "Male",
    number: "555-987-6543",
    date: "3 Days Ago",
    status: "Pending",
    location: "5786 Wolff Mill",
  },
  {
    name: "Sara Miller",
    email: "sara@example.com",
    image: "",
    gender: "Female",
    number: "555-567-8901",
    date: "2 Weeks Ago",
    status: "Active",
    location: "697 Brakus Road",
  },
  {
    name: "Michael Davis",
    email: "michael@example.com",
    image: "",
    gender: "Male",
    number: "555-234-5678",
    date: "Yesterday",
    status: "Active",
    location: "742 Jaunita Pine",
  },
];
