export const SidebarNavs = [
  {
    title: "Dashboard",
    path: "/dashboard",
    icon: "",
    img: "/images/icons/sidebar/home.svg",
    active: "/images/icons/sidebar/home_active.svg",
  },
  {
    title: "Users",
    path: "/dashboard/users",
    icon: "",
    img: "/images/icons/sidebar/user.svg",
    active: "/images/icons/sidebar/user_active.svg",
  },
  {
    title: "events",
    path: "/dashboard/events",
    icon: "",
    img: "/images/icons/sidebar/coupon.svg",
    active: "/images/icons/sidebar/coupon_active.svg",
  },
  {
    title: "Venues",
    path: "/dashboard/venues",
    icon: "",
    img: "/images/icons/sidebar/venues.svg",
    active: "/images/icons/sidebar/venues_active.svg",
  },
  {
    title: "kyc",
    path: "/dashboard/kyc",
    icon: "",
    img: "/images/icons/sidebar/kyc.svg",
    active: "/images/icons/sidebar/kyc_active.svg",
  },
  {
    title: "Services",
    path: "/dashboard/services",
    icon: "",
    img: "/images/icons/sidebar/user-dollar.svg",
    active: "/images/icons/sidebar/user-dollar_active.svg",
  },
  {
    title: "Support",
    path: "/dashboard/support",
    icon: "",
    img: "/images/icons/sidebar/support.svg",
    active: "/images/icons/sidebar/support_active.svg",
  },
  {
    title: "Report Issues",
    path: "/dashboard/reports",
    icon: "",
    img: "/images/icons/sidebar/report.svg",
    active: "/images/icons/sidebar/report_active.svg",
  },
  {
    title: "Roles & Permissions",
    path: "/dashboard/roles",
    icon: "",
    img: "/images/icons/sidebar/roles.svg",
    active: "/images/icons/sidebar/roles_active.svg",
  },

  {
    title: "Audit Trail",
    path: "/dashboard/audits",
    icon: "",
    img: "/images/icons/sidebar/audit.svg",
    active: "/images/icons/sidebar/audit_active.svg",
  },
  {
    title: "FAQ & Notifications",
    path: "/dashboard/faq_and_notifications",
    icon: "",
    img: "/images/icons/sidebar/faq.svg",
    active: "/images/icons/sidebar/faq_active.svg",
  },
  {
    title: "Settings",
    path: "/dashboard/settings",
    icon: "",
    img: "/images/icons/sidebar/settings.svg",
    active: "/images/icons/sidebar/settings_active.svg",
  },
];
